[project]
name = "hackthon-start"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"streamlit",
	"streamlit-code-editor",
	"python-dotenv",
	"chromadb>=1.1.1",
]

[dependency-groups]
dev = [
    "notebook>=7.4.7",
]
