[theme]
# Thème clair pour l'application
base = "light"
primaryColor = "#12aab2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"


[client]
showSidebarNavigation = false
